name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 #v2.4.0

    - name: Set up Go
      uses: actions/setup-go@424fc82d43fa5a37540bae62709ddcc23d9520d4 #v2.1.5
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v -coverprofile=coverage.cov ./kustomize ./cache

    - name: Tests coverage
      uses: codecov/codecov-action@f32b3a3741e1053eb607407145bc9619351dc93b #v2;1;0
      with:
        file: coverage.cov
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: Horusec Security
      run: |
        curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest
        horusec start -p . -n="kustomize" -u="https://api-horusec.zup.com.br"
