
name: Header license check

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 #v2.4.0
      - name: Check License and license year on prs
        uses: ZupIT/header-license-checker@635176fe2d08208c8256fd96cebae5c9a47e633c #0.0.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          FORCE_COLOR: 3